# Generated by Django 3.0.5 on 2020-04-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='cover',
            field=models.CharField(choices=[('P', 'Paperback'), ('C', 'Case Wrap'), ('D', 'Dust Jacket')], max_length=1),
        ),
    ]
