# Generated by Django 3.0.5 on 2020-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200411_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='print',
            name='cover',
            field=models.CharField(choices=[('P', 'Paperback'), ('C', 'Case Wrap'), ('D', 'Dust Jacket')], default='P', max_length=1),
        ),
    ]
