# Generated by Django 3.0.5 on 2020-04-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_book_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
        migrations.DeleteModel(
            name='AuthorName',
        ),
        migrations.AddField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(to='main_app.Translator'),
        ),
    ]
